"""fix relations

Revision ID: c486a7a791d3
Revises: 07e8ad73bc8c
Create Date: 2024-12-12 18:30:08.581242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c486a7a791d3'
down_revision: Union[str, None] = '07e8ad73bc8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema='payment_management') as batch_op:
        batch_op.add_column(sa.Column('id_apartment', sa.Integer(), nullable=False, comment='Идентификатор квартиры'))
        batch_op.drop_constraint('bill_unique_id_building_utility_account', type_='unique')
        batch_op.drop_constraint('bill_id_building_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'apartment', ['id_apartment'], ['id'], referent_schema='payment_management')
        batch_op.drop_column('utility_account')
        batch_op.drop_column('id_building')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema='payment_management') as batch_op:
        batch_op.add_column(sa.Column('id_building', sa.INTEGER(), autoincrement=False, nullable=False, comment='Идентификатор дома'))
        batch_op.add_column(sa.Column('utility_account', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Лицевой счет'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bill_id_building_fkey', 'building', ['id_building'], ['id'], referent_schema='payment_management')
        batch_op.create_unique_constraint('bill_unique_id_building_utility_account', ['id_building', 'utility_account'])
        batch_op.drop_column('id_apartment')

    # ### end Alembic commands ###
